language: node_js
node_js:
  - "7"
  - "8"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  # Check linting
  - "yarn lint"
  # Run test script
  - "yarn test"
